spring:
  application:
    name: erp
  profiles:
    active: default
  datasource:
    url: jdbc:h2:mem:erp
    username: root
    password: 12345
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    generate-ddl: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
    open-in-view: off
  flyway:
    enabled: false
