spring:
  application:
    name: erp
  profiles:
    active: default
  datasource:
    url: jdbc:h2:mem:erp
    username: root
    password: 12345
    driver-class-name: org.h2.Driver
  flyway:
    enabled: false

erp:
  jwt:
    secret: ${JWT_SECRET_KEY}
    accessTokenExpiration: 300 # 5m
    refreshTokenExpiration: 604800 # 7d

  file-extensions-config:
    allowed-file-extensions: jpg,jpeg,png,bmp

  photo-upload-directory-path:
    products: ${PRODUCT_PHOTOS_UPLOADS_DIRECTORY_PATH}
    user-profiles: ${USER_PROFILE_PHOTOS_UPLOADS_DIRECTORY_PATH}
