spring:
  application:
    name: erp
  profiles:
    active: default
  datasource:
    url: jdbc:h2:mem:erp
    username: root
    password: 12345
    driver-class-name: org.h2.Driver
  flyway:
    enabled: false

file-extensions-config:
  allowed-file-extensions: jpg,jpeg,png,bmp
