spring:
  application:
    name: erp
  profiles:
    active: default
  servlet:
    multipart:
      max-file-size: 1048576 # 1MB

erp:
  file-extensions-config:
    allowed-file-extensions: jpg,jpeg,png,bmp

  photo-upload-directory-path:
    products: ${PRODUCT_PHOTOS_UPLOADS_DIRECTORY_PATH}
    user-profiles: ${USER_PROFILE_PHOTOS_UPLOADS_DIRECTORY_PATH}
